blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/logeast/magic-lottery/discussions
    about: Use GitHub discussions for message-board style questions and discussions.
  - name: Discord Chat
    url: https://discord.gg/xKSsX84P
    about: Ask questions and discuss with other Magic Lottery users in real time.
